### PR TITLE
chore: Update request and sign-addon dependencies

### PR DESCRIPTION
**Pull request by pdehaan**
Ref #579

### CODE REVIEW

**Comment by pdehaan** [comment]
Looks like we may want to bump a **semver** dependency in **jetpack-validation** as well, but I'll [annoyingly] file a new bug and/or PR over there.


```sh
$ nsp check -o summary

(+) 1 vulnerabilities found
 Name     Installed   Patched   Path                                                  More Info
 semver   2.3.2       >=4.3.2   jpm@1.1.4 > jetpack-validation@0.0.6 > semver@2.3.2   https://nodesecurity.io/advisories/31
```

**Comment by kumar303** [comment]
Thanks @pdehaan , can you bump the package.json to get 0.0.7 of jetpack-validation? https://www.npmjs.com/package/jetpack-validation

**Comment by pdehaan** [comment]
> can you bump the package.json to get 0.0.7 of jetpack-validation

Done.

**Comment by kumar303** [comment]
oops, almost missed the follow-up. Thanks again!

**Pull request merged**
