### PR TITLE
Update commander to 2.9.0

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by kumar303** [comment]
I think once `npm install -g npm` is added to https://github.com/mozilla-jetpack/jpm/pull/420 (and merged) then this should build cleaner

**Comment by nikolas** [comment]
alright, i'll try that.

**Comment by nikolas** [comment]
I've rebased this on master. The 5.x failure looks intermittent.

**Comment by kumar303** [comment]
Yes, there is a known test timeout issue that we haven't been able to fix yet. I restarted the build just now to see if it gets to passing.

Could you spend some time manually testing out each jpm command after the commander upgrade? Could you also check the release notes to see if there are any breaking changes? The reason I ask is because we have pretty much zero test coverage of the commander invocation and configuration unfortunately.

**Comment by nikolas** [comment]
Yeah, I'll do that and get back to you.

**Comment by nikolas** [comment]
I've tested this branch successfully with these commands:

    jpm --help
    jpm -V
    jpm run -b `which firefox`
    jpm test -b `which firefox`
    jpm xpi
    jpm init

**Comment by kumar303** [comment]
Thanks for the additional testing!

**Pull request merged**
