### PR TITLE
jpm should not create blank tag <em:creator/>

### PR DESCRIPTION
**Pull request by jc3213**
This is about https://github.com/mozilla-jetpack/jpm/pull/502#discussion-diff-54294423 . I've created a patch previously #508 , but it doesn't changed the npm authors' part, so I create this new one

### CODE REVIEW

**Comment by kumar303** [comment]
Can you add a test for this that fails when the values are empty strings (`""`) but passes with your new changes (`undefined`) ?

**Comment by jc3213** [comment]
@kumar303 How about this?
```js
    it("`author` is '', do not ceate <em:creator/>", function() {
      var xml = setupRDF({ author: "" });
      var creator = xml.getElementsByTagName("em:creator");
      expect(creator.length).to.be.equal(0);
    });
```

**Comment by kumar303** [comment]
Yes, that looks like it will work. I think you'll also need an additional test that does `setupRDF({ author: undefined })`

**Comment by jc3213** [comment]
I've add the code following the method of 
```js
    it("multiprocess permission", function() {
      var xml = parseRDF(RDF.createRDF({ id: "1" }));
      expect(nodeExists(xml, "em:multiprocessCompatible")).to.be.equal(false);
      expect(getData(xml, "em:multiprocessCompatible")).to.be.equal(undefined);

      xml = parseRDF(RDF.createRDF({ id: "1", permissions: { multiprocess: true } }));
      expect(nodeExists(xml, "em:multiprocessCompatible")).to.be.equal(true);
      expect(getData(xml, "em:multiprocessCompatible")).to.be.equal("true");

      xml = parseRDF(RDF.createRDF({ id: "1", permissions: { multiprocess: false } }));
      expect(nodeExists(xml, "em:multiprocessCompatible")).to.be.equal(false);
      expect(getData(xml, "em:multiprocessCompatible")).to.be.equal(undefined);
});
```

**Comment by kumar303** [comment]
Thanks for the follow-up, looks great

**Pull request merged**
