### PR TITLE
Change default MAX_VERSION to *

### PR DESCRIPTION
**Pull request by wagnerand**
This avoids issues that happen when minversion in install.rdf is greater than MAX_VERSION

@kumar303 r?

### CODE REVIEW

**Comment by kumar303** [comment]
Can you confirm that this works? Did you try generating an add-on with this and submitting it to AMO?

This was tried before: https://github.com/mozilla-jetpack/jpm/pull/489

My understanding was that you could not submit an add-on to AMO but I could be wrong. There was more discussion about it in: https://github.com/mozilla/addons-server/issues/1548

**Comment by wagnerand** [comment]
Oh, yes, this probably depends on mozilla/addons-server#1548 as we currently allow "*" for webextensions only.

**Comment by kumar303** [comment]
https://github.com/mozilla/addons-server/issues/1548 is just calling for an adjustment to the UI. It isn't calling for a fix to the amo-validator (which I think is what throws the error, right?).

**Comment by wagnerand** [comment]
Yeah, sorry. So @jorgevillalobos are you ok with opening up max-version "*" for at least Firefox Desktop and Android (not sure whether Seamonkey supports jetpack add-ons) for all extensions?

**Comment by jvillalobos** [comment]
Yes, I'm okay with it.

**Comment by wagnerand** [comment]
Filed https://github.com/mozilla/amo-validator/pull/400

**Comment by wagnerand** [comment]
Confirmed that it works now that that amo-validator patch landed.

**Comment by kumar303** [comment]
Great. I will merge it now but I won't release a new jpm until the patch has landed on AMO.

**Comment by jc3213** [comment]
@kumar303  It seems amo already accept * as maximum version number for firefox now. I've signed my addon today with maximum version number *

**Pull request merged**
