### PR TITLE
feat: Add support for custom preferences page

### PR DESCRIPTION
**Pull request by nt1m**
Had to restart the repo from scratch and apply the changes manually

### CODE REVIEW

**Comment by kumar303** [comment]
See the original PR, https://github.com/mozilla-jetpack/jpm/pull/543, for discussion

**Comment by kumar303** [comment]
Let's do it! Thanks again.

**Comment by nt1m** [comment]
Thanks for merging! Added to the MDN docs too: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json

**Comment by kumar303** [comment]
Ah great, I was about to ask for that :)

**Pull request merged**
